# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showenv-deployment
spec:
  replicas: 5
  selector:
    matchLabels: # find associated pods based on the following label(s)
      app: showenv
  template: # all pods of this deployment will be created from this template
    metadata:
      labels: # add label(s) to the pods, so deployments (or services) can find them
        app: showenv
    spec:
      containers:
      - name: showenv
        image: proksch/showenv
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector: # find matching pods based on the following label(s)
    app: showenv
  ports:
  - port: 1234
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: my-service
      port:
        number: 1234